job:
  output_folder: ${RABBITS_PROJECT_HOME}/benchmarks/ior/output
  run_dir: ${RABBITS_JOB_OUTPUT_FOLDER}/${RABBITS_JOB_FOLDER_NAME}
  conf: ${RABBITS_JOB_RUN_DIR}/conf
  result: ${RABBITS_JOB_RUN_DIR}/result
ior:
  file_sharing_cmd: "-F"
  block_size: RABBITS_SUBS_BLOCK_SIZE
  block_size_cmd: "-b=${RABBITS_IOR_BLOCK_SIZE}"
  transfer_size: RABBITS_SUBS_TRANSFER_SIZE
  transfer_size_cmd: "-t=${RABBITS_IOR_TRANSFER_SIZE}"
  sync_options_cmd: "-Y -e"
  output_format_cmd: "CSV"
  iteration_cmd: "-i 5"
  reorder_task_cmd: "-C"
  interface_cmd: POSIX
  collective_cmd: ""
  operation_cmd: "-w"
  interface_cmd: "-a ${RABBITS_IOR_INTERFACE}"
  output_file_prefix: ${RABBITS_JOB_RESULT}/${RABBITS_NAME}_${RABBITS_JOB_NODES}_${RABBITS_JOB_PPN}_${RABBITS_IOR_BLOCK_SIZE}_${RABBITS_IOR_TRANSFER_SIZE}_write
